Implement MIDI for tablature
rism-digital/verovio pull request #2568
Opened 2022-01-12 12:53 UTC by paul-bayleaf

Implement MIDI for tablature.
(I had a pull request this earlier but seems to have disappeared, probably my error.)

2022-01-12 14:08 UTC, lpugin commented
I am not sure what happen. That one was merged https://github.com/rism-digital/verovio/pull/2402/files

As far as I can see, this PR contains some code that we discussed. Namely the https://github.com/rism-digital/verovio/pull/2568/files#diff-17a7bcdc2c2e792707144ffd6d70cbfb0b3129d832f9c9f4d1271767e64c5f87R718-R727 loop for adding notes of the previous staff. That caused the last note(s) not to be played. As far as I remember I passed you some information on how to change this and do it with and functor end.

2022-01-18 15:12 UTC, lpugin commented
@paul-bayleaf are you sure this PR is still valid? I think MIDI rendering has been merged already and that this code is obsolete. Please double check.

2022-01-18 15:23 UTC, paul-bayleaf commented
Yes this PR is still valid.  The develop-tab branch does not have the 'rule of holds' logic to extend a note's noteOff time beyond the note's rhythm.  This PR also implements the various new COURSETUNING_ values.

2022-01-18 15:39 UTC, lpugin requested changes
Great, thanks for checking.

2022-01-18 15:39 UTC, lpugin commented on src/staff.cpp
> +}
This should be moved the the Layer. That is, move it to a `Layer::GenerateMIDIEnd(FunctorParams *functorParams)` with probably exactly the same code. I don't think we have seen encoding with multiple layers, but if we have some then the code should be triggered at the end of each layer and not of each staff (only).

2022-01-18 18:22 UTC, lpugin approved these changes

2022-01-18 18:22 UTC, merged

2022-01-18 18:22 UTC, lpugin commented
Thanks! And sorry for delaying the merge.