Store UUID of original element in @corresp
rism-digital/verovio pull request #2904
Opened 2022-05-31 15:30 UTC by Monceber

This change adds code that stores UUID of original element when it's being clones to the `@corresp` attribute (when applicable). This allow us to track back some of the elements, that are being cloned in the process and new IDs are generated for them as the result. In most cases these elements are KeySig/Clef/MeterSig/etc. (elements of the ScoreDef).

`GetElementAttr` is also changed to get original element whenever found object has @corresp set.

2022-06-01 06:42 UTC, ahankinson commented
Is this still using UUIDs? (i.e., [UUIDv4](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random))) Or is it just generic XML IDs? IIRC the XML IDs assigned by Verovio are not actually UUIDs anymore...

2022-06-01 07:14 UTC, lpugin requested changes

2022-06-01 07:48 UTC, rettinghaus commented
But it doesn't change the original MEI, does it? From my point of view this is a very MEI-ish way to not store additional information in the SVG output, but still have the ability to track down where clefs, grouping symbols etc. originate from in the toolkit. 
At the moment I don't see a better way for handling spanning control elements as it is implemented right now, but it is not very elegant.

2022-06-02 09:29 UTC, Monceber commented on src/object.cpp
> +    for (Object *layer : layers) {
Yes, I guess it does make sense to use existing Process() functionality. I'm not quite sure about storing `m_child` though - it is quite convenient to save it, but it seems to break the principle behind comparison functors that we have right now. I.e. none of them store any data at the moment, and we would be changing that here.

2022-06-02 09:51 UTC, Monceber commented on src/object.cpp
> +    for (Object *layer : layers) {
Alternatively, we could go with Functor approach:

```c++
class FindLayerUuidWithinStaffDefParams : public FunctorParams {
public:
    explicit FindLayerUuidWithinStaffDefParams(const std::string &Uuid)
    {
        m_uuid = Uuid;
        m_object = NULL;
    }

    Object *m_object;
    std::string m_uuid;
};
```

Change `FindElementInLayerStaffDefsByUUID` to take these params, and in toolkit we'd have to call `Process()`:

```c++
Functor findByUuid(&Object::FindElementInLayerStaffDefsByUUID);
FindLayerUuidWithinStaffDefParams params(xmlId);
m_doc.GetDrawingPage()->Process(&findByUuid, &params);
```

This way we won't need to call `FindElementInLayerStaffDefsByUUID` twice and we search recursively through the tree.

2022-06-02 10:49 UTC, lpugin commented on src/object.cpp
> +    for (Object *layer : layers) {
Even better! I like it.

2022-06-02 10:50 UTC, lpugin approved these changes

2022-06-02 10:50 UTC, merged