Fix typo when iohumdrum.cpp sets turn@form (every turn was being set to "lower").
rism-digital/verovio pull request #3412
Opened 2023-05-08 22:41 UTC by gregchapman-dev

2023-05-08 22:57 UTC, gregchapman-dev commented
OK, it's actually two fixes.

2023-05-09 02:43 UTC, craigsapp commented on src/iohumdrum.cpp
> +    turn->SetForm(invertedQ ? turnLog_FORM_lower : turnLog_FORM_upper);
Thanks!  I was wondering a few weeks ago why the turns were upside down (but I never bothered to check).

2023-05-09 02:47 UTC, craigsapp commented
> Fix typo when setting turn@form (every turn's form was set to lower).
Fix crash in LayerElement::CalcLayerOverlap when sameDirElement is true, but stemInterface is NULL.
Fix crash in Layer::GetAtPos when this->GetFirst() returns NULL, by moving the NULL check a bit earlier.

Only the first commit should be PRed to the develop humdrum branch.  The other two should go to the `develop` branch.  @lpugin can either say that as well or he can approve merging into the `develop-humdrum` branch and then I will do a PR to the `develop` branch.

2023-05-09 08:46 UTC, craigsapp approved these changes

2023-05-09 09:28 UTC, lpugin requested changes
Yes, please make a distinct PR to develop for the changes in layer.cpp and layerelement.cpp

2023-05-09 22:33 UTC, gregchapman-dev commented
New PR for the layer.cpp and layerelement.cpp fixes is PR #3413.

2023-05-09 22:38 UTC, gregchapman-dev commented
OK, I have made the same layer.cpp fix tweak here now that I made on develop, for consistency.  Do you need me to remove the two NULL checks from this PR?  Or can I leave them in place, so humdrum-develop can benefit from them as well?

2023-05-10 02:46 UTC, craigsapp commented
> Do you need me to remove the two NULL checks from this PR? Or can I leave them in place, so humdrum-develop can benefit from them as well, prior to any merge-back from develop?

The best thing is to remove them from `develop-humdrum`, and then I will pull `develop` into `develop-humdrum` (so they will end up there from your PR to `develop`).

2023-05-10 06:29 UTC, lpugin approved these changes

2023-05-10 06:29 UTC, merged