Fix/java build
rism-digital/verovio pull request #3545
Opened 2023-11-14 11:28 UTC by bwbohl

Building the Java Toolkit failed

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Java version: 21, openjdk.jdk
OS name: "mac os x", version: "12.6.5", arch: "aarch64", family: "mac"

Maven reported to use `target` elements instead of `task` elements in the `pom.xml`

This PR changes the pom accordingly

2023-11-14 11:53 UTC, rettinghaus approved these changes

2023-11-14 11:54 UTC, rettinghaus commented
@bwbohl please rebase on latest develop and resolve conflicts.

2023-11-15 12:09 UTC, lpugin requested changes
Please rebase

2023-11-15 13:12 UTC, bwbohl commented
done

2023-11-15 16:42 UTC, lpugin approved these changes
Thanks

2023-11-16 14:43 UTC, merged

2023-11-20 10:46 UTC, bwbohl commented
thanks for merging ;-)