fix #3633: output a single midi lyrics event per note with all syls in the note
rism-digital/verovio pull request #3634
Opened 2024-03-22 08:32 UTC by fernandoherreradelasheras

2024-03-22 08:40 UTC, rettinghaus commented
I would expect such addition in `VisitVerse` (or `VisitSyl`).

2024-03-22 08:44 UTC, fernandoherreradelasheras commented
> I would expect such addition in `VisitVerse` (or `VisitSyl`).

Ok, thanks! I'll take a look into it

2024-06-05 08:53 UTC, rettinghaus commented
@fernandoherreradelasheras any luck?

2024-07-19 11:18 UTC, fernandoherreradelasheras commented
Sorry, got this on hold while experimenting with different approaches to multiple verse lyrics. I will get back to this soon

2024-10-06 13:55 UTC, lpugin requested changes

2024-10-06 13:55 UTC, lpugin commented on src/midifunctor.cpp
> +        m_midiFile->addLyric(m_midiTrack, startTime * m_midiFile->getTPQ(), m_currentNoteLyrics);
Just move this to a new `GenerateMIDIFunctor::VisitVerseEnd` and remove the lookup here.

2024-10-08 08:12 UTC, lpugin commented
Please re-open with the requested changes.

2024-10-08 08:12 UTC, closed without merging